<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoursesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'ANALYSIS',
                'courseCode' => 'CEF 201',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'LINEAR ALGEBRA',
                'courseCode' => 'CEF 203',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'INTRODUCTION TO COMPUTING',
                'courseCode' => 'CEF 205',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'COMPUTER PROGRAMMING 1',
                'courseCode' => 'CEF 207',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'BOOLEAN ALGEBRA AND LOGIC CIRCUITS',
                'courseCode' => 'CEF 211',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'CIRCUIT ANALYSIS',
                'courseCode' => 'CEF 261',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'DIGITAL ELECTRONICS 1',
                'courseCode' => 'CEF 263',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'PHYSICS FOR ELECTRICAL ENGINEERING 1',
                'courseCode' => 'CEF 269',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'USE OF ENGLISH 1',
                'courseCode' => 'ENG 101',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 1,
                'name' => 'FUNCTIONAL FRENCH 1',
                'courseCode' => 'FRE 101',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'C/C++ PROGRAMMING',
                'courseCode' => 'CEF 238',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'COMPUTER ARCHITECTURE',
                'courseCode' => 'CEF 250',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'ALGEBRA',
                'courseCode' => 'CEF 254',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'CIVICS AND ETHICS',
                'courseCode' => 'CVE 100',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'ANALOG ELECTRONICS 1',
                'courseCode' => 'EEF 260',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'PHYSICS FOR ENGINEERING 2',
                'courseCode' => 'EEF 262',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'CONTROL ENGINEERING INSTRUMENTATION',
                'courseCode' => 'EEF 264',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'DIGITAL ELECTRONICS 2',
                'courseCode' => 'EEF 268',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'USE OF ENGLISH 2',
                'courseCode' => 'ENG 102',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'FUNCTIONAL FRENCH 2',
                'courseCode' => 'FRE 102',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facultyId' => 1,
                'userId' => 4,
                'semesterId' => 2,
                'name' => 'SPORTS',
                'courseCode' => 'SPT 100',
                'level' => '200',
                'status' => 'compulsory',
                'creditValue' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
