<?php

namespace Database\Seeders;

use App\Models\Semester;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SemesterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('semesters')->insert([

            [
                'semester' => 1,
                'year' => 2023,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2023,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2023,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2024,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2024,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2024,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2025,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2025,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2025,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2026,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2027,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2027,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2027,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2028,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2028,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2028,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2029,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2029,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2029,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2030,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2030,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2030,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2031,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2031,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2031,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2032,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2032,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2032,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2033,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2033,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2033,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2034,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2034,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2034,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2035,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2035,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2035,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2036,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2036,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2036,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2037,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2037,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2037,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2038,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2038,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2038,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2039,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2039,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2039,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2040,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2040,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2040,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2041,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2041,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2041,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2042,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2042,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2042,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2043,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2043,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2043,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2044,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2044,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2044,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2045,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2045,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2045,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2046,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2046,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2046,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2047,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2047,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2047,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2048,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2048,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2048,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2049,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2049,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2049,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2050,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2050,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2050,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2051,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2051,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2051,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2052,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2052,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2052,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2053,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2053,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2053,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2054,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2054,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2054,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2055,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2055,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2055,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2056,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2056,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2056,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2057,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2057,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2057,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2058,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2058,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2058,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2059,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2059,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2059,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 1,
                'year' => 2060,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 2,
                'year' => 2060,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'semester' => 3,
                'year' => 2060,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
